### ISSUE TITLE
Farm middle plot harvesting

### ISSUE THREAD

**Issue by averyfukawa** [Jelled1st/Project_ShowOff#11]
I don't know if it's a bug specifically with the center plot, since all other plots behave just fine, but it refuses to be harvested by swiping down or up, only left or right. 
All the others seem to work just fine. And it's also still finicky whether it even harvests properly or not. It might have to do with the kind of input required, if it's a hold and drag, or something else.

**Comment by Jelled1st** [comment]
When your mouse moved so quick that the ray-cast keeps hitting IControllables the controller assumed that a new controllable was selected rather than a drag. This has been resolved. every IControlalble is compared to the current selected (and a null check), if they are not the same a drag action is started
